### PR TITLE
Added pubsub to core and geo facade is ready

### PR DESCRIPTION
**Pull request by landau**
I've added a pubsub class that may be useful for some modules and exposed to h5api users, if it isn't useful lets remove it later.

More importantly, I've implemented a wrapper for geolocation.  I have not yet tested watch position on a mobile device, but I'm sure it works fine.

Critiques welcome.

### CODE REVIEW

**Comment by getify** [comment]
Thanks so much for the contribution! Will take a look at the example usage API a bit more indepth soon. At first glance, I had a few questions.

Also, can you explain what the purpose of the PubSub stuff will be in this API?

**Comment by landau** [comment]
I'm not actually sure what pubsub would be good for right now. It may be useful in some apis like file system or xhr, where async calls are used.  I wrote it in case I ever come across a possible use when writing one of the wrappers. Mostly looking for thoughts on usefulness in the project. :)

**Comment by landau** [comment]
I've just added a FormData facade thats ready for a pull too :)

**Comment by getify** [comment]
@landau can you please keep separate facades in separate pull requests? want to keep discussions orderly, and want to have the freedom to merge them in separately as necessary.

**Comment by landau** [comment]
Yeah, sorry!

**Comment by landau** [comment]
Is the only way to separate pull requests to branch? I just realized when I pushed yesterday that it was automatically added to this pull request.

**Comment by getify** [comment]
i'm actually not sure on that. but i would say it's probably a good idea to fork/branch for each anyway.

**Comment by landau** [comment]
Okay.  From here on out,  Separate branches.

**Pull request closed without merging**
